# version: '3.9'

services:  # Docker Compose file consist of one or more services
  app: # Name of our service, this is just the service which run our docker file
    build: # It's just says that we want to build the docker file inside our current directory
      context: . # The root directory we are running command from 
      args:
        - DEV=true # We have a build argument set to True
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app # We are mapping the map directory of our project to the app directory inside our container,
                  # THe reason we add this because we want the updates that we make to our code in our local project to be reflected
                  # in the running container in real time. Automatic Sync
    command: > # Commnd that's used to run the service, We can override it with Docker compose run (command)
      sh -c "python manage.py runserver 0.0.0.0:8000" 